{% set version = "5.1.2" %} # semver: (x.y.z)
{% set x,y,z = version.split('.') %}
{% set version_ffmpeg_style = x ~ '.' ~ y if z == "0" else version %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  url: https://ffmpeg.org/releases/ffmpeg-{{ version_ffmpeg_style }}.tar.gz
  sha256: 87fe8defa37ce5f7449e36047171fed5e4c3f4bb73eaccea8c954ee81393581c
  patches:
    - patches/pkgconfig_generate_windows_llvm.patch  # [win]

{% set build = 5 %}
{% if license_family == 'gpl' %}
    {% set build = build + 100 %}
{% endif %}

build:
  number: {{ build }}
  string: {{ license_family }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
  # seems to be major version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    # clangxx is required for support of the nvidia encoders and decoders
    - clangxx  # [linux64]
    - autotools_clang_conda  # [win]
    - pkg-config
    - libtool  # [not win]
    - nasm  # [not (osx and x86_64)]
    # osx_64 needs yasm due to https://stackoverflow.com/questions/58796267/building-for-macos-but-linking-in-object-file-built-for-free-standing
    - yasm  # [osx and x86_64]
    - lame  # [not win]
    - make  # [not win]
    - m2-sed  # [win]
    # makedef uses the printf command which is provided by coreutils
    # - m2-coreutils  # [win]
  host:
    - bzip2
    - freetype
    - fontconfig
    - gnutls  # [not win]
    - libiconv  # [osx]
    - libxml2
    {% if license_family == 'gpl' %}
    - x264
    - x265
    {% endif %}
    - libvpx  # [not win]
    - zlib
    - openh264
    - lame  # [not win]
    - gmp  # [unix]
    - libva  # [linux64]
    - aom
    - svt-av1
    - ffnvcodec-headers  # [linux64 or win]
    - libopus

{% set grep = "grep" %}  # [unix]
{% set grep = "findstr" %}  # [win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -hide_banner -codecs
    - ffmpeg -hide_banner -protocols
    - ffmpeg -hide_banner -protocols | {{ grep }} "https"
    - ffmpeg -hide_banner -codecs | {{ grep }} "libmp3lame"       # [unix]
    - ffmpeg -hide_banner -codecs | {{ grep }} "DEVI.S\ zlib"
    - ffmpeg -hide_banner -codecs | {{ grep }} "DEV.LS h264"
    - ffmpeg -hide_banner -codecs | {{ grep }} "libopenh264"
    - ffmpeg -hide_banner -codecs | {{ grep }} "vaapi"            # [linux64]
    - ffmpeg -hide_banner -codecs | {{ grep }} "libaom"
    - ffmpeg -hide_banner -codecs | {{ grep }} "libsvtav1"
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avdevice",
        "swresample",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale",
        "avutil",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\{{ each_ffmpeg_lib }}.lib exit 1  # [win]
    {% endfor %}
    # Windows dynamic libraries have a suffix
    {% set ffmpeg_libs = [
        "avdevice-59",
        "swresample-4",
        "avfilter-8",
        "avcodec-59",
        "avformat-59",
        "swscale-6",
        "avutil-57",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - if not exist %PREFIX%\\Library\\bin\\{{ each_ffmpeg_lib }}.dll exit 1  # [win]
    {% endfor %}
    {%- if license_family == 'gpl' %}
    - ffmpeg -hide_banner -buildconf | {{ grep }} "enable-gpl"
    - ffmpeg -hide_banner -codecs | {{ grep }} "libx264"
    - ffmpeg -hide_banner -codecs | {{ grep }} "libx265"
    - test -f $PREFIX/lib/libpostproc${SHLIB_EXT}         # [unix]
    - if not exist %PREFIX%\\Library\\bin\\postproc-56.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\postproc.lib exit 1  # [win]
    # https://trac.ffmpeg.org/wiki/Null
    - ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=8 -vcodec libx264 -f null -
    - ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=8 -vcodec libx265 -f null -
    {%- endif %}
    {%- if license_family == 'lgpl' %}
    - ffmpeg -hide_banner -buildconf | {{ grep }} "disable-gpl"
    - test ! $(ffmpeg -hide_banner -codecs | grep "libx264")     # [unix]
    - test ! $(ffmpeg -hide_banner -codecs | grep "libx265")     # [unix]
    - test ! -f $PREFIX/lib/libpostproc${SHLIB_EXT}              # [unix]
    - if exist %PREFIX%\\Library\\bin\\postproc-55.dll exit 1    # [win]
    - if exist %PREFIX%\\Library\\lib\\postproc.lib exit 1       # [win]
    {%- endif %}
    # Verify nvidia codecs on linux
    {% set nvcodecs = [
        "h264_nvenc",
        "hevc_nvenc",
        "mjpeg_cuvid",
        "mpeg1_cuvid",
        "mpeg2_cuvid",
        "mpeg4_cuvid",
        "vc1_cuvid",
        "vp8_cuvid",
        "vp9_cuvid"
    ] %}
    {% for nvcodec in nvcodecs %}
    # Make sure to include a space in there to ensure we get an exact match
    - ffmpeg -hide_banner -codecs | {{ grep }} " {{ nvcodec }} "  # [linux64 or win]
    {% endfor %}
    # https://trac.ffmpeg.org/wiki/Null
    - ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=8 -vcodec libopenh264 -f null -

about:
  home: https://www.ffmpeg.org/
  license: GPL-2.0-or-later  # [license_family=='gpl']
  license: LGPL-2.1-or-later  # [license_family=='lgpl']
  license_file:
    - COPYING.GPLv2            # [license_family=='gpl']
    - COPYING.GPLv3            # [license_family=='gpl']
    - COPYING.LGPLv2.1         # [license_family=='lgpl']
    - COPYING.LGPLv3           # [license_family=='lgpl']
  license_family: GPL  # [license_family=='gpl']
  license_family: LGPL  # [license_family=='lgpl']
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://git.ffmpeg.org/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - hmaarrfk
    - danielballan
    - jakirkham
    - 183amir
    - patricksnape
    - ocefpaf
    - sdvillal
    - carlodri
    - benjaminrwilson
    - matthiasdiener
    - h-vetinari
