{% set version = "5.0.1" %} # semver: (x.y.z)
{% set x,y,z = version.split('.') %}
{% set version_ffmpeg_style = x ~ '.' ~ y if z == "0" else version %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  - url: https://ffmpeg.org/releases/ffmpeg-{{ version_ffmpeg_style }}.tar.gz
    sha256: 840c012766ceb1a95ec92fcbe51d80024a74b1b3134c92c2ff64a6f8165e9059


build:
  number: 3
  run_exports:
  # seems to be major version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - nasm  # [not (win or (osx and x86_64))]
    # osx_64 needs yasm due to https://stackoverflow.com/questions/58796267/building-for-macos-but-linking-in-object-file-built-for-free-standing
    - yasm  # [osx and x86_64]
    - lame  # [not win]
    - make  # [not win]
  host:
    - bzip2  # [not win]
    - freetype  # [not win]
    - gnutls  # [not win]
    - libiconv  # [osx]
    - libxml2  # [not win]
    - x264  # [not win]
    - x265  # [not win]
    - libvpx  # [not win]
    - zlib  # [not win]
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [unix]
    - libva  # [linux and not (ppc64le or aarch64)]
    - aom  # [unix]
    - svt-av1  # [unix]
  run:
    - svt-av1  # [unix]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libx264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libx265"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "vaapi"  # [linux and not (ppc64le or aarch64)]
    - ffmpeg -loglevel panic -codecs | grep "libaom"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libsvtav1"  # [unix]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale",
        "avutil",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}${SHLIB_EXT}  # [unix]
    {% endfor %}

about:
  home: https://www.ffmpeg.org/
  license: GPL-3.0-or-later
  license_file: COPYING.GPLv3  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://git.ffmpeg.org/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - danielballan
    - jakirkham
    - 183amir
    - patricksnape
    - ocefpaf
    - sdvillal
    - carlodri
    - benjaminrwilson
    - matthiasdiener
    - h-vetinari
