{% set version = "2.8.6" %}

package:
    name: ffmpeg
    version: {{ version }}

source:
    fn: ffmpeg-{{ version }}.tar.gz
    url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz
    md5: 7b9449795790c46331dae2c6e8e28f15

build:
    number: 1

requirements:
    build:
        - pkg-config      # [unix]
        - libtool         # [unix]
        - yasm
        - gcc             # [osx]
        - posix           # [win]
        - m2w64-binutils  # [win]
        - c99-to-c89      # [win]
        - msinttypes      # [win and py<34]
        - x264            # [unix]
        - zlib 1.2*
    run:
        - libgcc          # [osx]
        - x264            # [unix]
        - zlib 1.2*

test:
    commands:
        - ffmpeg --help

about:
    home: http://www.ffmpeg.org/
    license: GPL 2
    summary: Cross-platform solution to record, convert and stream audio and video.

extra:
    recipe-maintainers:
        - danielballan
        - jakirkham
