travis:
  secure:
    BINSTAR_TOKEN: FnHeYeUQEcfys4wNrXDpzQf0Y/hxoL8Y/ivPmXYW8wADv+YfrIDK2n6XbYgDfTXFAQuMepUVQq6HcTJW0hHQG2B3E2+BLboj4bYjBEFYYr0SuMdJDPTlaCu7qZmwD06KxklOgNw4mojCD5YJUJZONxNccBFncx19JM9Hdqwdqwy/WlM6RVAi6NVtno66yjerjViw6kfel0EnNZgo76JWp/TtUkKv/IzddEMoOmK7IKvdaCTfGRW7Z0mbb9XXt3aHcqtlvv0cULojCxwI2jk+ZyHNORpPOXEYayl1A/7agcEccZxXAv1eA+DZ5UJy5tEQwQIYEemOSk4WJ27xnwMfqWfGqQOQCyzAXe2t4LdTOwn2FJnIpTGUdstO0vBUR1iMRvrKfwUrPLo5qiXyVXnV4E8u1DOTbwQB2zJ8tnjclsSAxGni0xxMTtQiMqrdA5Sj805pZcme+pIISF/ebDrOIeqOQQONSg7Z2/gLTyqCG0UFx/a2Ni5EeaitI+P3s1r5oVK5LhydRM5nLZx2BT1PmFwoC2Fik1bQYFxdosEF8ZE3aHRPZfME3dL7tKguGqJ43gHBZmvg7y5hcRgdC4LDcXPu0AYTMptX17xTHIxuvZNPRYXKicdlOr7Pl+9IlZ26rAisPjcHT1k11bdlzTZN/aXvjiDIu3PlWAAFZrYIw5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
